###############################################################################
# Secrets. Passwords/tokens are GENERATED by Terraform and stored in Secrets
# Manager - never written into .tf files. Secrets are encrypted with the
# customer-managed secrets KMS key. Rotation is configured (documented).
#
# Note: generated values transit Terraform state during creation; state lives
# in the encrypted, private S3 backend, which is the accepted mitigation.
###############################################################################

resource "random_password" "db" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "random_password" "cache_auth" {
  length  = 64
  special = false # ElastiCache AUTH tokens must be alphanumeric
}

# --- RDS master credentials ---
resource "aws_secretsmanager_secret" "db" {
  name        = "${var.name_prefix}/rds/master"
  description = "RDS master credentials for ${var.name_prefix}"
  kms_key_id  = aws_kms_key.secrets.arn
  tags        = local.common_tags
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    engine   = "postgres"
    dbname   = var.db_name
    host     = aws_db_instance.this.address
    port     = 5432
  })
}

# Rotation: automatic rotation configured on a 30-day schedule.
# A rotation Lambda is required for the actual rotation logic; here we document
# and wire the schedule. In apply, attach a rotation function ARN.
resource "aws_secretsmanager_secret_rotation" "db" {
  count               = var.rotation_lambda_arn == "" ? 0 : 1
  secret_id           = aws_secretsmanager_secret.db.id
  rotation_lambda_arn = var.rotation_lambda_arn
  rotation_rules {
    automatically_after_days = 30
  }
}

# --- ElastiCache AUTH token ---
resource "aws_secretsmanager_secret" "cache_auth" {
  name        = "${var.name_prefix}/elasticache/auth-token"
  description = "ElastiCache AUTH token for ${var.name_prefix}"
  kms_key_id  = aws_kms_key.secrets.arn
  tags        = local.common_tags
}

resource "aws_secretsmanager_secret_version" "cache_auth" {
  secret_id     = aws_secretsmanager_secret.cache_auth.id
  secret_string = jsonencode({ auth_token = random_password.cache_auth.result })
}

variable "rotation_lambda_arn" {
  description = "ARN of a rotation Lambda for RDS credentials (optional; enables scheduled rotation)"
  type        = string
  default     = ""
}
